apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: daylight-cert
  namespace: daylight
spec:
  secretName: daylight-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: daylight.liem.zip
  dnsNames:
  - daylight.liem.zip